### ISSUE TITLE
JEI Still display objects blocked by stage [More Tool] [Bug]

### ISSUE THREAD

**Issue by TheLynk** [Darkhax-Minecraft/ItemStages#70] opened 2021-10-04 19:08 UTC
[img](https://ibb.co/9w1PJtL)
exemple

**Comment by Darkhax** [comment] 2021-10-04 23:11
This is a duplicate of https://github.com/Darkhax-Minecraft/ItemStages/issues/61

**Closed as completed by Darkhax** 2021-10-04 23:11 UTC
